#!/usr/bin/python

# This script flashes the focused window when the focus moves. It acts as a visual guide to what window is currently focused.

import i3ipc
from functools import partial
import time
import os


def flash(opacity_steps, ipc, event):
    # Need disable functionality to make screenshot tools work.
    exists = os.path.isfile("/tmp/disable_focus_flasher")
    if exists:
        print("disabled")
        return

    focused_window = ipc.get_tree().find_focused()
    # Only 1 window no need to flash, if we only got 1 on the workspace.
    windows = focused_window.workspace().descendants()
    if len(windows) == 1:
        return

    for op in opacity_steps:
        focused_window.command(f"opacity {op}")
        time.sleep(0.005)


if __name__ == "__main__":
    # Generate opacity fractions up to 100%
    opacity_steps = []
    step_count = 20
    for i in range(1, step_count):
        opacity_steps.append(i / step_count)
    # Final step should be default opacity
    # TODO handle default opacity below 100%
    opacity_steps.append(1)

    ipc = i3ipc.Connection()
    ipc.on(i3ipc.Event.WINDOW_FOCUS, partial(flash, opacity_steps))
    ipc.main()
