#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc query -M --names | xargs -n1 -I{} bspc monitor {} -d 1 2 3 4 5 6 7 8 9 0
python3 ~/.config/bspwm/monitors.py >> ~/monitors.log

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
#bscp config focused_border_color fff
bspc config focused_border_color "$(xrdb -query | grep color12 | cut -f 2)"
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config pointer_follows_monitor true
bspc config merge_overlapping_monitors true
bspc config single_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

~/.config/bspwm/bar.sh

wmname LG3D
