name: Run Unittests


on: [ push ]

jobs:

  run_test:
    runs-on: ubuntu-22.04
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Run tests
      shell: bash
      run: |
        # Simulate the same directory structure as when the dotfiles are installed locally
        set -x
        export HOME="$(pwd)"
        export OVERRIDE_DOTFILES_GIT_DIR="$(pwd)/.git"
        source ~/bin/scripts/functions.sh
        config update
        ~/.config/dotfiles/unit_test.sh

